# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cf91866ba2814f3dc098946f6e42f5d9b9d56bf4cf2777e3f199122d7b7e429a7750bef6c0e19659e1f750ef4530e4bb64f24ba4a69656b188055014745f10f

test:
  secret_key_base: 2fba069d528f8c3c84842e61d3350069ad58fa1cb8abe2f086cc2df8d8bcffb67122474641afc6697b8d1effe2e30ca2798722190961c0b3444e87d1eadb6b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
